# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-test

steps:
- script: echo Hello, world!
- script: mkdir azagent;cd azagent;curl -fkSL -o vstsagent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.191.1/vsts-agent-linux-x64-2.191.1.tar.gz;tar -zxvf vstsagent.tar.gz; if [ -x "$(command -v systemctl)" ]; then ./config.sh --environment --environmentname "ubuntu-test" --acceptteeeula --agent $HOSTNAME --url https://dev.azure.com/th26017744/ --work _work --projectname 'Test' --auth PAT --token v6tcbp27owrhnze6sjvtcbneqbfkpabkejvzjqbsievvurn74bhq --runasservice; sudo ./svc.sh install; sudo ./svc.sh start; else ./config.sh --environment --environmentname "ubuntu-test" --acceptteeeula --agent $HOSTNAME --url https://dev.azure.com/th26017744/ --work _work --projectname 'Test' --auth PAT --token v6tcbp27owrhnze6sjvtcbneqbfkpabkejvzjqbsievvurn74bhq; ./run.sh; fi
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    mkdir build
    cd build
    ../configure
    make
  displayName: 'Run a multi-line script'
